import { create } from "zustand";
import type { Document, Entity, EntityFolder, EntityType, FieldDefinition, KnownProject, RelationType } from "../types/core";
type ActiveView = "writing" | "worldbuilding";
interface AppState { coreInitialized:boolean; initStatus:string; initError:string|null; projectId:string|null; projectPath:string|null; activeView:ActiveView; selectedDocumentId:string|null; selectedEntityId:string|null; showCreateEntityModal:boolean; showCreateDocumentModal:boolean; rootDocuments:Document[]; childrenMap:Record<string,Document[]>; knownProjects:KnownProject[]; entityTypes:EntityType[]; entitiesByType:Record<string,Entity[]>; entityFolders:EntityFolder[]; rootEntities:Entity[]; entitiesByFolder:Record<string,Entity[]>; fieldDefinitionsByType:Record<string,FieldDefinition[]>; relationTypes:RelationType[]; draggingId:string|null; setCoreInitialized:(v:boolean)=>void; setInitStatus:(v:string)=>void; setInitError:(v:string|null)=>void; setProjectId:(v:string|null)=>void; setProjectPath:(v:string|null)=>void; setActiveView:(v:ActiveView)=>void; setSelectedDocumentId:(v:string|null)=>void; setSelectedEntityId:(v:string|null)=>void; setRootDocuments:(v:Document[])=>void; setChildren:(id:string,v:Document[])=>void; addDocument:(v:Document)=>void; updateDocument:(v:Document)=>void; removeDocument:(id:string)=>void; moveDocument:(id:string,parentId:string|null,index:number)=>void; reorderDocuments:(parentId:string|null,draggedId:string,targetId:string)=>void; setDraggingId:(id:string|null)=>void; setKnownProjects:(v:KnownProject[])=>void; resetProjectState:()=>void; setEntityTypes:(v:EntityType[])=>void; setEntitiesForType:(id:string,v:Entity[])=>void; setEntityFolders:(v:EntityFolder[])=>void; setRootEntities:(v:Entity[])=>void; setEntitiesForFolder:(folderId:string,v:Entity[])=>void; setFieldDefinitionsForType:(typeId:string,v:FieldDefinition[])=>void; setRelationTypes:(v:RelationType[])=>void; addRelationType:(v:RelationType)=>void; setShowCreateEntityModal:(v:boolean)=>void; setShowCreateDocumentModal:(v:boolean)=>void; }
const normalize=(docs:Document[])=>docs.map((d,i)=>({...d,sort_order:i}));
export const useAppStore=create<AppState>((set)=>({
 coreInitialized:false,initStatus:"Starting…",initError:null,projectId:null,projectPath:null,activeView:"writing",selectedDocumentId:null,selectedEntityId:null,showCreateEntityModal:false,showCreateDocumentModal:false,rootDocuments:[],childrenMap:{},knownProjects:[],entityTypes:[],entitiesByType:{},entityFolders:[],rootEntities:[],entitiesByFolder:{},fieldDefinitionsByType:{},relationTypes:[],draggingId:null,
 setCoreInitialized:v=>set({coreInitialized:v}),setInitStatus:v=>set({initStatus:v}),setInitError:v=>set({initError:v}),setProjectId:v=>set({projectId:v}),setProjectPath:v=>set({projectPath:v}),setActiveView:v=>set({activeView:v}),setSelectedDocumentId:v=>set({selectedDocumentId:v}),setSelectedEntityId:v=>set({selectedEntityId:v}),setRootDocuments:v=>set({rootDocuments:v}),setChildren:(id,v)=>set(s=>({childrenMap:{...s.childrenMap,[id]:v}})),
 addDocument:doc=>set(s=>doc.parent_id?{childrenMap:{...s.childrenMap,[doc.parent_id]:[...(s.childrenMap[doc.parent_id]??[]),doc]}}:{rootDocuments:[...s.rootDocuments,doc]}),
 updateDocument:doc=>set(s=>({rootDocuments:s.rootDocuments.map(d=>d.id===doc.id?doc:d),childrenMap:Object.fromEntries(Object.entries(s.childrenMap).map(([k,v])=>[k,v.map(d=>d.id===doc.id?doc:d)]))})),
 removeDocument:id=>set(s=>({rootDocuments:s.rootDocuments.filter(d=>d.id!==id),childrenMap:Object.fromEntries(Object.entries(s.childrenMap).map(([k,v])=>[k,v.filter(d=>d.id!==id)])),selectedDocumentId:s.selectedDocumentId===id?null:s.selectedDocumentId})),
 moveDocument:(id,parentId,index)=>set(s=>{let moving:Document|undefined;const roots=s.rootDocuments.filter(d=>{if(d.id===id){moving=d;return false}return true});const maps:Object=Object.fromEntries(Object.entries(s.childrenMap).map(([k,v])=>[k,v.filter(d=>{if(d.id===id){moving=d;return false}return true})]));if(!moving)return s;moving={...moving,parent_id:parentId};const list=parentId===null?roots:(maps as Record<string,Document[]>)[parentId]??[];list.splice(Math.max(0,Math.min(index,list.length)),0,moving);if(parentId===null)return{rootDocuments:normalize(list),childrenMap:Object.fromEntries(Object.entries(maps as Record<string,Document[]>).map(([k,v])=>[k,normalize(v)]))};return{rootDocuments:normalize(roots),childrenMap:{...(maps as Record<string,Document[]>),[parentId]:normalize(list)}}}),
 reorderDocuments:(parentId,draggedId,targetId)=>set(s=>{const list=parentId===null?[...s.rootDocuments]:[...(s.childrenMap[parentId]??[])];const from=list.findIndex(d=>d.id===draggedId);const to=list.findIndex(d=>d.id===targetId);if(from===-1||to===-1)return s;const[item]=list.splice(from,1);list.splice(to,0,item);if(parentId===null)return{rootDocuments:normalize(list)};return{childrenMap:{...s.childrenMap,[parentId]:normalize(list)}}}),
 setDraggingId:id=>set({draggingId:id}),
 setKnownProjects:v=>set({knownProjects:v}),resetProjectState:()=>set({rootDocuments:[],childrenMap:{},entityTypes:[],entitiesByType:{},entityFolders:[],rootEntities:[],entitiesByFolder:{},fieldDefinitionsByType:{},relationTypes:[],selectedDocumentId:null,selectedEntityId:null,projectPath:null}),setEntityTypes:v=>set({entityTypes:v}),setEntitiesForType:(id,v)=>set(s=>({entitiesByType:{...s.entitiesByType,[id]:v}})),setEntityFolders:v=>set({entityFolders:v}),setRootEntities:v=>set({rootEntities:v}),setEntitiesForFolder:(folderId,v)=>set(s=>({entitiesByFolder:{...s.entitiesByFolder,[folderId]:v}})),setFieldDefinitionsForType:(typeId,v)=>set(s=>({fieldDefinitionsByType:{...s.fieldDefinitionsByType,[typeId]:v}})),setRelationTypes:v=>set({relationTypes:v}),addRelationType:v=>set(s=>({relationTypes:[...s.relationTypes,v]})),setShowCreateEntityModal:v=>set({showCreateEntityModal:v}),setShowCreateDocumentModal:v=>set({showCreateDocumentModal:v})
}));
